### ISSUE TITLE
[Question] within zeno.ipynb, how did you arrive at optimal hyper parameters 

### ISSUE THREAD

**Issue by abhishekms1047** [garrowat/zenobot#1]
I saw that you are passing these hyper parameters for your neural networks . Can you please explain on how you arrived at it and how do you know that it is optimal.
```
TEXT = data.Field(lower=True, tokenize=list)
bs=64; bptt=8; n_fac=42; n_hidden=128

TEXT3 = data.Field(lower=True, tokenize=list)
bs=64; bptt=8; n_fac=42; n_hidden2=512
```

1. Is there any methodology like Bayesian optimization,Grid Search,Genetic algos?

**Comment by garrowat** [comment]
Hi, sure! I'm quite novice so I'm afraid I can't provide much in the way of methodology.

- bs=64: this was used during part 7 of the fast.ai course, and seemed to work well enough for Zenobot. I might try bs=1 for prediction as I hear that works well
- bptt=8: again, suggested by fast.ai
- n_fac=42: same reason
- n_hidden=512: once my dataset got larger, I found that increasing the hidden layers improved the model
